{{ $fullname :=  include "chart.fullname" . }}
{{ $selectorLabels :=  include "chart.selectorLabels" .  }}
{{ $serviceLabels :=  include "chart.serviceLabels" .  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
  ports:
    {{- if $.Values.node.substrateApiSidecar.enabled }}
    - port: 8080
      name: api-sidecar
    {{- end }}
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
---
{{range $i := until (.Values.node.replicas | int) }}
{{- if $.Values.node.perNodeServices.createClusterIPService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}
  labels:
    {{- $serviceLabels | nindent 4 }}
    instance: {{ $fullname }}-{{ $i }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
    - port: 9615
      name: prometheus
{{- end }}
---
{{- if $.Values.node.perNodeServices.createP2pNodePortService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}-relay-chain-p2p
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - name: p2p
      port: 30333
      targetPort: 30333
{{- end }}
---
{{- if and $.Values.node.collator.isParachain $.Values.node.perNodeServices.createP2pNodePortService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}-para-chain-p2p
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - name: p2p
      port: 30334
      targetPort: 30334
{{- end }}
---
{{ end }}
