name: Check and Test

on: [pull_request]

permissions:
  contents: read

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      toolchain: ${{ steps.get_toolchain.outputs.TOOLCHAIN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --tags
      - run: pip3 install yq
      - name: Get Build Version
        id: get_version
        run: ./scripts/check-version.sh
        shell: bash
      - name: Get Toolchain Version
        id: get_toolchain
        run: |
          echo "##[set-output name=TOOLCHAIN;]$(cat rust-toolchain)"

  check:
    name: Check and test
    runs-on: ubuntu-latest
    needs: [get-version]

    steps:
      - uses: actions/checkout@master
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ needs.get-version.outputs.toolchain }}
          target: wasm32-unknown-unknown
      - name: Install sccache
        env:
          TEMP: ${{ runner.temp }}
        run: |
          curl -L https://github.com/gruntwork-io/fetch/releases/download/v0.3.7/fetch_linux_amd64 --output $TEMP/fetch
          chmod +x $TEMP/fetch
          $TEMP/fetch --repo="https://github.com/mozilla/sccache" --tag="~>0.2.15" --release-asset="^sccache-v[0-9.]*-x86_64-unknown-linux-musl.tar.gz$" $TEMP
          tar -xvf $TEMP/sccache-v*-x86_64-unknown-linux-musl.tar.gz -C $TEMP
          mv $TEMP/sccache-v*-x86_64-unknown-linux-musl/sccache $TEMP/sccache
          rm -rf $TEMP/sccache-v*-x86_64-unknown-linux-musl $TEMP/sccache-v*-x86_64-unknown-linux-musl.tar.gz $TEMP/fetch
          chmod +x $TEMP/sccache
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Cache sccache
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/cache
          key: ${{ runner.os }}-cargo-build-cache-debug-${{ hashFiles('**/Cargo.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-cache-debug-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-build-cache-debug-
      - name: Cargo format
        uses: actions-rs/cargo@v1
        env:
          RUSTC_WRAPPER: ${{ runner.temp }}/sccache
          SCCACHE_DIR: ${{ runner.temp }}/cache
        with:
          command: fmt
      - name: Cargo check
        uses: actions-rs/cargo@v1
        env:
          RUSTC_WRAPPER: ${{ runner.temp }}/sccache
          SCCACHE_DIR: ${{ runner.temp }}/cache
        with:
          command: check
      - name: Cargo test
        uses: actions-rs/cargo@v1
        env:
          RUSTC_WRAPPER: ${{ runner.temp }}/sccache
          SCCACHE_DIR: ${{ runner.temp }}/cache
        with:
          command: test

  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: [get-version]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        volumes:
          - "/tmp/sccache:/data"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@master
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
        driver-opts: network=${{ job.services.redis.network }}
    - name: Stop Redis
      env:
        SERVICE_ID: ${{ job.services.redis.id }}
      run: |
        docker stop $SERVICE_ID
        sudo rm -rf /tmp/sccache
    - name: Cache Docker sccache
      uses: actions/cache@v2
      with:
        path: /tmp/sccache
        key: ${{ runner.os }}-docker-sccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-sccache-
    - name: Prepare Redis with cache
      timeout-minutes: 1
      id: prepare-redis
      env:
        SERVICE_ID: ${{ job.services.redis.id }}
        NETWORK: ${{ job.services.redis.network }}
      run: |
        docker start $SERVICE_ID
        while true; do
          echo "Sleeping for 5 seconds"
          sleep 5
          STATUS=$(/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" $SERVICE_ID)
          echo $STATUS
          [[ "$STATUS" == "healthy" ]] && break
        done

        # github service containers don't support args. As a workaround we configure redis as a cache whilst running
        /usr/bin/docker run --network=$NETWORK redis redis-cli -h redis CONFIG SET maxmemory 500mb
        /usr/bin/docker run --network=$NETWORK redis redis-cli -h redis CONFIG SET maxmemory-policy allkeys-lru

        # get ip address of redis container
        ip=$(/usr/bin/docker container inspect --format="{{print .NetworkSettings.Networks.$NETWORK.IPAddress }}" $SERVICE_ID)
        echo "::set-output name=ip::$ip"
    - name: Generate tags
      id: generate-tags
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        TAG=$(echo "$BRANCH" | sed 's/\//-/g')
        echo "##[set-output name=branch_tag;]ghcr.io/digicatapult/vitalam-node:$TAG";
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        load: true
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=${{ runner.temp }}/docker-buildx-cache
        cache-to: type=local,dest=${{ runner.temp }}/docker-buildx-cache-temp,mode=max
        context: .
        build-args: |
          BUILD_BASE_VERSION=nightly-2021-11-09-alpine3.14
          BUILD_CONFIG_SCCACHE_LOCAL=
          BUILD_CONFIG_SCCACHE_REDIS=redis://${{ steps.prepare-redis.outputs.ip }}:6379
        file: ./Dockerfile
        platforms: linux/amd64
        tags: |
          ghcr.io/digicatapult/vitalam-node:branch-${{ steps.generate-tags.outputs.branch_tag }}
        labels: |
          org.opencontainers.image.title=vitalam-node
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.source=${{ github.event.repository.html_url }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ needs.get-version.outputs.version }}
          org.opencontainers.image.created=${{ needs.get-version.outputs.build_date }}
    - name: Publish image
      run: docker push --all-tags ghcr.io/digicatapult/vitalam-node
    - name: Flush Redis to disk
      env:
        NETWORK: ${{ job.services.redis.network }}
      run: |
        /usr/bin/docker run --network=$NETWORK redis redis-cli -h redis SAVE
